### ISSUE TITLE
Ubuntu 22.04 App Center Installs gThumb snap that does not work

### ISSUE THREAD

**Issue by dadr** [nbuechner/gthumb-snap#1]
Gruesse Herr Buechner!  And Thank you for the work you do on open source.

I have a computer with Ubuntu 24.04.   I want to install gThumb, and I tried using the App Center from Ubuntu to do this.  I installed gThumb version 3.12.6 and the App Center thinks it's installed.  However the program (snap) does not run.  I have tried logging out and in again, and to start it several times.  

If it helps, I get this when I try to start it from the command line:

```
tom@bigmac:~$ gthumb-unofficial.gthumb
/snap/gthumb-unofficial/18/usr/bin/gthumb: symbol lookup error: /snap/gthumb-unofficial/18/usr/bin/gthumb: undefined symbol: g_string_free_and_steal
```

Vielen Dank!

**Comment by nbuechner** [comment]
The last snap update should fix that. Please try again.

**Comment by dadr** [comment]
Yes, it did.  All works well now.  Vielen Dank noch einmal.
